name: project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animate_do: ^3.3.4
  lottie: ^3.1.0
  flutter_svg: ^2.0.10+1
  pin_code_fields: ^8.0.1
  clipboard: ^0.1.3
  image_picker: 1.0.8
  url_launcher: ^6.2.6
  shared_preferences: ^2.2.3
  intro_screen_onboarding_flutter: ^1.0.0
  just_audio: ^0.9.37
  video_player: ^2.8.6
  flick_video_player: ^0.8.0
  youtube_player_flutter: ^9.0.1
  dio: ^5.4.3+1
  carousel_slider: ^4.2.1
  flutter_bloc: ^8.1.5
  flutter_widget_from_html_core: ^0.14.12
  get_it: ^7.6.7
  kiwi: ^5.0.0
  shimmer: ^3.0.0
  flutter_screenutil: ^5.9.1
  google_maps_flutter: ^2.5.3
  maps_launcher: ^2.2.1
  geocoding: ^3.0.0
  geolocator: ^11.1.0
  chart_sparkline: ^1.0.15+1
  circular_countdown_timer: ^0.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/lotties/
    - assets/svg/
    - assets/fonts/
  fonts:
    - family: inter
      fonts:
        - asset: assets/fonts/inter.ttf
    - family: courgette
      fonts:
        - asset: assets/fonts/courgette.ttf

